nav:
  - Inicio: index.md
  - Facultades:
      - Ciencias Económicas y Empresariales: economicas_empresariales.md
      - Exactas y Naturales: exactas_naturales.md
      - Ciencias del comportamiento: comportamiento.md
      - Ciencias de la Salud: salud.md
      - Sociales y Humanidades: sociales_humanidades.md
      - Jurídicas y Políticas: juridicas_politicas.md
      - Ingenierías y Arquitectura: ingenierias_arquitectura.md